=== Qivex/scotland-yard/static/boards/board.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Scotland Yard Board",
	"type": "object",
	"required": ["image", "stations", "tickets", "turnCount", "visibleTurns"],
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"type": "string",
			"format": "uri-reference"
		},
		"image": {
			"description": "Background image of the board",
			"type": "object",
			"required": ["src", "size"],
			"properties": {
				"src": {
					"description": "URI of the image",
					"type": "string",
					"format": "uri-reference"
				},
				"size": {
					"description": "Dimensions of the image",
					"type": "array",
					"additionalItems": false,
					"items":[
						{
							"description": "Width",
							"type": "integer"
						},
						{
							"description": "Height",
							"type": "integer"
						}
					]
				}
			}
		},
		"stations": {
			"description": "All stations on the board that can be visited",
			"type": "array",
			"items": {
				"description": "Coordinates of a single station on the map",
				"type": "array",
				"additionalItems": false,
				"items": [
					{
						"description": "Latitude",
						"type": "number"
					},
					{
						"description": "Longitude",
						"type": "number"
					}
				]
			}
		},
		"connections": {
			"description": "All connections of the stations",
			"type": "array",
			"items": {
				"description": "All available connections of a single station",
				"type": "array",
				"items": [
					{
						"description": "Connections available when using a taxi",
						"type": "array",
						"items": {
							"description": "Taxi connection",
							"type": "integer"
						}
					},
					{
						"description": "Connections available when using a bus",
						"type": "array",
						"items": {
							"description": "Bus connection",
							"type": "integer"
						}
					},
					{
						"description": "Connections available when using a subway",
						"type": "array",
						"items": {
							"description": "Subway connection",
							"type": "integer"
						}
					},
					{
						"description": "Connections available when using a black ticket",
						"type": "array",
						"items": {
							"description": "Black ticket connection",
							"type": "integer"
						}
					}
				]
			}
		},
		"tickets": {
			"description": "Number of tickets the players start with",
			"type": "array",
			"minItems": 2,
			"maxItems": 2,
			"items": [
				{
					"description": "Number of tickets Mr.X starts with",
					"$ref": "#/$defs/tickets"
				},
				{
					"description": "Number of tickets the detectives start with",
					"$ref": "#/$defs/tickets"
				}
			]
		},
		"turnCount": {
			"description": "Amount of turns for Mr.X to win",
			"type": "integer"
		},
		"visibleTurns": {
			"description": "All turns by Mr.X which are visible for everyone",
			"type": "array",
			"items": {
				"description": "Visible turn",
				"type": "integer"
			}
		},
		"startLocations": {
			"description": "All locations where players could start from",
			"type": "array",
			"items": {
				"description": "Possible start",
				"type": "integer"
			}
		}
	},
	"$defs": {
		"tickets": {
			"type": "array",
			"additionalItems": false,
			"items": [
				{
					"description": "Taxi tickets",
					"type": "integer"
				},
				{
					"description": "Bus tickets",
					"type": "integer"
				},
				{
					"description": "Subway tickets",
					"type": "integer"
				},
				{
					"description": "Black tickets",
					"type": "integer"
				},
				{
					"description": "Double tickets",
					"type": "integer"
				}
			]
		}
	}}

=== Qivex/scotland-yard/static/boards/board1.json
{
	"$schema": "board.schema.json",
	"image": {
		"src": "boards/board1.png",
		"size": [400,300]
	},
	"stations": [
		[[-75,60],[1,4],[1,3],[2]],
		[[-200,65],[0,4],[0],[3]],
		[[-75,285],[3],[4],[0]],
		[[-200,290],[2,4],[0],[1]],
		[[-130,180],[0,1,3],[2]]
	],
	"tickets": [
		[10,4,4,1,2],
		[8,8,8,0,0]
	],
	"turnCount": 30,
	"visibleTurns": [3,7,10],
	"startLocations": [0,1,2,3,4]
}
