=== Qivex/scotland-yard/static/boards/gamestate.schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"title": "Scotland Yard Gamestate",
	"type": "object",
	"required": ["boardID", "players"],
	"additionalProperties": false,
	"properties": {
		"$schema": {
			"type": "string",
			"format": "uri-reference"
		},
		"boardID": {
			"description": "Identifier of the board",
			"type": "string"
		},
		"players": {
			"description": "UUIDs of involved players (first player is Mr.X)",
			"type": "array",
			"minItems": 2,
			"items": {
				"description": "Player UUID",
				"type": "string",
				"format": "uuid"
			}
		},
		"starts": {
			"description": "Location where each player starts",
			"type": "array",
			"items": {
				"description": "Start place",
				"type": "integer"
			}
		},
		"turns": {
			"description": "All turns that were already played",
			"type": "array",
			"items": {
				"description": "A single turn (includes moves of all players)",
				"type": "array",
				"items": {
					"description": "A single move (includes all ticket uses by a player in a single move)",
					"oneOf": [
						{
							"description": "A move using a single ticket",
							"type": "object",
							"required": ["ticket", "target"],
							"additionalProperties": false,
							"properties": {
								"ticket": {"$ref": "#/$defs/ticket"},
								"target": {"$ref": "#/$defs/target"}
							}
						},
						{
							"description": "A move using a double ticket",
							"type": "object",
							"required": ["firstTicket", "firstTarget", "secondTicket", "secondTarget"],
							"additionalProperties": false,
							"properties": {
								"firstTicket": {"$ref": "#/$defs/ticket"},
								"firstTarget": {"$ref": "#/$defs/target"},
								"secondTicket": {"$ref": "#/$defs/ticket"},
								"secondTarget": {"$ref": "#/$defs/target"}
							}
						}
					]
				}
			}
		}
	},
	"$defs": {
		"ticket": {
			"description": "The type of ticket that was used",
			"type": "integer",
			"minimum": 0,
			"maximum": 3
		},
		"target": {
			"description": "The station to which the player moved",
			"type": "integer"
		}
	}
}

=== Qivex/scotland-yard/static/boards/examplestate.json
{
	"$schema": "gamestate.schema.json",
	"boardID": "board1",
	"players": ["mrx", "det1", "det2"],
	"starts": [4,1,0],
	"turns": [
		[
			{"ticket": 0, "target": 3},
			{"ticket": 0, "target": 4},
			{"ticket": 2, "target": 2}
		],
		[
			{"firstTicket": 2, "firstTarget": 1, "secondTicket": 1, "secondTarget": 0}
		]
	]
}
